Repository ministryofjustice/legal-framework-api, pull requests merged in 2022-11, with the labels that each got.

#780 Fix: Remove latest_incident from non Domestic Abuse proceedings
  db/seed_data/proceeding_type_merits_task.yml
Labels: ready for review

#784 AP-3493: Include LASPO as application level task
  db/populators/merits_task_populator.rb
  db/seed_data/proceeding_type_merits_task.yml
  spec/requests/merits_tasks_controller_swagger_spec.rb
  spec/services/merits_task_service_spec.rb
  spec/services/questions_service_spec.rb
  swagger/v1/swagger.yaml
Labels: ready for review

#788 AP-3591: Update display_rule for latest_incident_details question
  app/services/merits_task_service.rb
  app/services/questions_service.rb
  db/seed_data/proceeding_type_merits_task.yml
  spec/services/questions_service_spec.rb
Labels: approved, UAT

#787 AP-3489 replace reason_for_new_application with vary_order merits_task
  db/populators/merits_task_populator.rb
  db/seed_data/proceeding_type_merits_task.yml
Labels: approved, UAT

#793 AP-3593: Split opponent questions
  db/populators/merits_task_populator.rb
  db/seed_data/proceeding_type_merits_task.yml
  spec/models/merits_task_spec.rb
  spec/models/proceeding_type_spec.rb
  spec/requests/civil_merits_questions_controller_swagger_spec.rb
  spec/requests/merits_tasks_controller_swagger_spec.rb
  spec/services/merits_task_service_spec.rb
  spec/services/questions_service_spec.rb
  swagger/v1/swagger.yaml
Labels: UAT

#807 AP-3670: Section 8 seed data
  app/models/proceeding_type_scope_limitation.rb
  app/models/scope_limitation.rb
  app/services/proceeding_type_service.rb
  db/migrate/20221128165100_remove_proceeding_type_scope_limitations.rb
  db/populators/proceeding_type_scope_limitations_populator.rb
  db/populators/proceeding_type_service_levels_populator.rb
  db/schema.rb
  db/seed_data/proceeding_type_service_levels.yml
  db/seeds.rb
  spec/populators/proceeding_type_service_levels_populator_spec.rb
  spec/services/proceeding_type_populator_spec.rb
  spec/services/proceeding_type_service_spec.rb
Labels: ready for review
