Repository ministryofjustice/legal-framework-api, pull requests merged in 2022-10, with the labels that each got.

#751 update comment
  db/seed_data/matter_types.yml
Labels: ready for review

#728 Fix: Add an ECR cleanup job
  .circleci/config.yml
  bin/delete_ecr_images
Labels: ready for review

#754 AP-3476: Extend merits task list questions
  .rubocop.yml
  app/controllers/civil_merits_questions_controller.rb
  app/models/merits_task.rb
  app/services/merits_task_service.rb
  app/services/questions_service.rb
  config/routes.rb
  db/migrate/20221010132246_add_display_rules_to_proceeding_type_merits_tasks.rb
  db/populators/merits_task_populator.rb
  db/populators/proceeding_type_merits_task_populator.rb
  db/schema.rb
  db/seed_data/proceeding_type_merits_task.yml
  lib/tasks/swag.rake
  public/schemas/civil_merits_questions.json.erb
  spec/models/proceeding_type_spec.rb
  spec/requests/civil_merits_questions_controller_swagger_spec.rb
  spec/services/questions_service_spec.rb
  swagger/v1/swagger.yaml
Labels: ready for review

#758 Fix: Update the swagger parameter description
  spec/requests/civil_merits_questions_controller_swagger_spec.rb
Labels: ready for review

#761 ap-3546: fix for proceeding_type_service failing with new proceeding …
  app/services/proceeding_type_service.rb
  spec/services/proceeding_type_service_spec.rb
Labels: approved

#760 AP-3545: Update ScopeLimitationsPopulator
  db/populators/scope_limitations_populator.rb
  spec/requests/proceeding_type_scopes_controller_spec.rb
  spec/services/proceeding_type_scopes_service_spec.rb
Labels: ready for review

#771 Fix/remove backtraces
  app/services/merits_task_service.rb
  app/services/proceeding_type_service.rb
  app/services/threshold_waiver_service.rb
  spec/requests/merits_tasks_controller_swagger_spec.rb
  spec/requests/proceeding_types_controller_swagger_spec.rb
  spec/services/merits_task_service_spec.rb
  spec/services/proceeding_type_service_spec.rb
  spec/services/threshold_waiver_service_spec.rb
  swagger/v1/swagger.yaml
Labels: approved, Discussion

#772 AP-3529: Conditionally hide the latest incident details task
  app/services/merits_task_service.rb
  app/services/questions_service.rb
  db/seed_data/proceeding_type_merits_task.yml
  spec/requests/civil_merits_questions_controller_swagger_spec.rb
  spec/services/questions_service_spec.rb
  swagger/v1/swagger.yaml
Labels: approved

#773 AP-3571: Update section 8 tasks seed
  app/services/questions_service.rb
  db/populators/merits_task_populator.rb
  db/seed_data/proceeding_type_merits_task.yml
  spec/models/proceeding_type_spec.rb
  spec/requests/civil_merits_questions_controller_swagger_spec.rb
  spec/requests/merits_tasks_controller_swagger_spec.rb
  spec/services/merits_task_service_spec.rb
  spec/services/questions_service_spec.rb
  swagger/v1/swagger.yaml
Labels: approved, UAT
