Repository ministryofjustice/legal-framework-api, pull requests merged in 2022-08, with the labels that each got.

#691 AP-3357 Populate pt scopes
  app/models/scope_limitation.rb
  db/populators/proceeding_type_scope_populator.rb
  db/populators/scope_limitations_populator.rb
  db/seed_data/proceeding_type_scopes.yml
  db/seed_data/scope_limitations.yml
  db/seeds.rb
  spec/models/scope_limitation_spec.rb
  spec/populators/scope_limitations_populator_spec.rb
Labels: ready for review

#696 AP-3370 Improve test suite times
  spec/models/default_cost_limitation_spec.rb
  spec/models/matter_type_spec.rb
  spec/models/merits_task_spec.rb
  spec/models/proceeding_type_scope_spec.rb
  spec/models/proceeding_type_spec.rb
  spec/models/scope_limitation_spec.rb
  spec/models/service_level_spec.rb
  spec/populators/client_involvement_types_populator_spec.rb
  spec/populators/proceeding_type_service_levels_populator_spec.rb
  spec/populators/scope_limitations_populator_spec.rb
  spec/populators/service_levels_populator_spec.rb
  spec/rails_helper.rb
  spec/requests/client_involvement_types_controller_spec.rb
  spec/requests/merits_tasks_controller_spec.rb
  spec/requests/proceeding_types/searches_spec.rb
  spec/requests/proceeding_types/threshold_waivers_spec.rb
  spec/requests/proceeding_types_spec.rb
  spec/requests/swagger_docs/client_involvement_types_spec.rb
  spec/requests/swagger_docs/merits_tasks_spec.rb
  spec/requests/swagger_docs/new_threshold_waivers_spec.rb
  spec/requests/swagger_docs/proceeding_type_searches_spec.rb
  spec/requests/swagger_docs/proceeding_types_spec.rb
  spec/requests/swagger_docs/threshold_waivers_spec.rb
  spec/requests/threshold_waivers_controller_spec.rb
  spec/services/merits_task_service_spec.rb
  spec/services/proceeding_type_full_text_search_spec.rb
  spec/services/proceeding_type_populator_spec.rb
  spec/services/proceeding_type_service_spec.rb
  spec/services/threshold_waiver_service_spec.rb
Labels: approved

#693 Ap 3362 add full section 8 to proceeding types
  app/models/proceeding_type.rb
  app/services/proceeding_type_full_text_search.rb
  app/services/proceeding_type_service.rb
  app/services/threshold_waiver_service.rb
  db/migrate/20220728101235_add_full_section8_to_proceeding_types.rb
  db/schema.rb
  spec/requests/proceeding_types/searches_spec.rb
  spec/requests/proceeding_types/threshold_waivers_spec.rb
  spec/requests/proceeding_types_spec.rb
  spec/requests/threshold_waivers_controller_spec.rb
  spec/services/proceeding_type_full_text_search_spec.rb
  spec/services/proceeding_type_service_spec.rb
  spec/services/threshold_waiver_service_spec.rb
  swagger/v1/swagger.yaml
Labels: approved

#698 ap-3350: add proceeding_type_defaults endpoint
  app/controllers/proceeding_type_defaults_controller.rb
  app/services/proceeding_type_defaults_service.rb
  config/routes.rb
  spec/requests/proceeding_type_defaults_controller_spec.rb
  spec/requests/swagger_docs/proceeding_type_defaults_spec.rb
  spec/services/proceeding_type_defaults_service_spec.rb
  swagger/v1/swagger.yaml
Labels: approved

#702 Fix: proceeding_type_defaults swagger
  spec/requests/swagger_docs/proceeding_type_defaults_spec.rb
  swagger/v1/swagger.yaml
Labels: ready for review

#703 AP-3381 Add Scope user Inputs table
  app/models/scope_limitation.rb
  app/models/scope_limitation_user_input.rb
  app/models/scope_user_input.rb
  db/migrate/20220804111406_create_scope_user_inputs.rb
  db/migrate/20220804112224_create_scope_limitation_user_inputs.rb
  db/schema.rb
  spec/factories/scope_limitations.rb
  spec/factories/scope_user_inputs.rb
  spec/models/scope_limitation_spec.rb
  spec/models/scope_user_input_spec.rb
Labels: approved

#704 AP-3371 Populate ProceedingTypes with new section 8 proceedings
  app/services/proceeding_type_populator.rb
  db/seed_data/proceeding_types.yml
  spec/requests/proceeding_types/searches_spec.rb
  spec/services/proceeding_type_full_text_search_spec.rb
  spec/services/proceeding_type_populator_spec.rb
Labels: approved

#708 Ap 3351 proceeding type scopes endpoint
  Gemfile
  Gemfile.lock
  app/controllers/proceeding_type_scopes_controller.rb
  app/services/proceeding_type_scopes_service.rb
  app/validators/json_validator.rb
  config/routes.rb
  public/schemas/proceeding_type_scopes.json.erb
  spec/requests/proceeding_type_defaults_controller_spec.rb
  spec/requests/proceeding_type_scopes_controller_spec.rb
  spec/requests/swagger_docs/proceeding_type_scopes_spec.rb
  spec/services/proceeding_type_scopes_service_spec.rb
  spec/validators/json_validator_spec.rb
  swagger/v1/swagger.yaml
Labels: approved

#711 Ap 3396 proceeding type defaults json schema
  app/controllers/proceeding_type_defaults_controller.rb
  app/services/proceeding_type_defaults_service.rb
  spec/requests/proceeding_type_defaults_controller_spec.rb
  spec/requests/swagger_docs/proceeding_type_defaults_spec.rb
  spec/services/proceeding_type_defaults_service_spec.rb
Labels: ready for review

#712 AP-3373 Solution to eligible scopes without using join table
  app/models/client_involvement_type.rb
  app/models/proceeding_type_scope.rb
  app/models/scope_limitation.rb
  app/services/eligible_scopes_service.rb
  config/eligible_scopes.yml
  db/migrate/20220810143751_drop_proceeding_type_scopes_table.rb
  db/populators/proceeding_type_scope_populator.rb
  db/schema.rb
  db/seed_data/proceeding_type_scopes.yml
  db/seeds.rb
  spec/models/client_involvement_type_spec.rb
  spec/models/proceeding_type_scope_spec.rb
  spec/models/scope_limitation_spec.rb
  spec/services/eligible_scopes_service_spec.rb
Labels: approved

#721 AP-3407A Alter proceeding_type_defaults to not take service level as param
  app/models/scope_limitation.rb
  app/models/scope_user_input.rb
  app/models/service_level.rb
  app/services/eligible_scopes_service.rb
  app/services/proceeding_type_defaults_service.rb
  app/services/proceeding_type_scopes_service.rb
  config/eligible_scopes.yml
  public/schemas/proceeding_type_defaults.json.erb
  spec/requests/proceeding_type_defaults_controller_spec.rb
  spec/requests/proceeding_type_scopes_controller_spec.rb
  spec/requests/swagger_docs/proceeding_type_defaults_spec.rb
  spec/services/eligible_scopes_service_spec.rb
  spec/services/proceeding_type_defaults_service_spec.rb
  spec/services/proceeding_type_scopes_service_spec.rb
  swagger/v1/swagger.yaml
Labels: approved, UAT
