Repository ministryofjustice/legal-framework-api, pull requests merged in 2023-01, with the labels that each got.

#841 Fix: Update the github action versions
  .github/workflows/codeql-analysis.yml
  .github/workflows/docker-image-scan.yml
Labels: ready for review

#842 AP-3728: Remove merits_task endpoint
  app/controllers/merits_tasks_controller.rb
  app/services/merits_task_service.rb
  spec/requests/civil_merits_questions_controller_swagger_spec.rb
  spec/requests/merits_tasks_controller_swagger_spec.rb
  spec/services/merits_task_service_spec.rb
  swagger/v1/swagger.yaml
Labels: approved

#869 AP-3749: Update s8 substantive cost limit seeding
  app/models/proceeding_type.rb
  app/services/proceeding_type_populator.rb
  db/populators/default_cost_limitation_populator.rb
  db/seed_data/default_cost_limitations.yml
  spec/models/proceeding_type_spec.rb
  spec/populators/default_cost_limitation_populator_spec.rb
  spec/services/proceeding_type_service_spec.rb
Labels: approved, UAT

#853 Update Ruby to v3.2.0
  .circleci/config.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: UAT

#882 Use reusable snyk workflow to scan docker images
  .github/workflows/docker-image-scan.yml
Labels: ready for review
