Repository ministryofjustice/legal-framework-api, pull requests merged in 2024-12, with the labels that each got.

#1504 AP-5540: Add defaults for PLF matter type
  README.md
  app/services/eligible_scopes_service.rb
  config/eligible_scopes.yml
  db/populators/default_cost_limitation_populator.rb
  db/seed_data/default_cost_limitations.yml
  db/seed_data/proceeding_type_service_levels.yml
  docs/matter_types.md
  spec/populators/proceeding_type_service_levels_populator_spec.rb
  spec/services/eligible_scopes_service_spec.rb
Labels: approved, ready for review

#1510 Fix: Correct PBM40E proceeding type and tests
  db/seed_data/proceeding_types.yml
  spec/requests/proceeding_types/searches_controller_swagger_spec.rb
  spec/services/proceeding_type_full_text_search_spec.rb
  swagger/v1/swagger.yaml
Labels: approved

#1506 AP-5377: Update LFA for PLF merits tasks
  app/services/questions_service.rb
  db/populators/merits_task_populator.rb
  db/populators/proceeding_type_merits_task_populator.rb
  db/seed_data/proceeding_type_merits_task/public_law_family.yml
  spec/populators/merits_task_populator_spec.rb
  spec/populators/proceeding_type_merits_task_populator_spec.rb
  spec/services/questions_service_spec.rb
Labels: approved, ready for review

#1514 AP-4410: Add test for PLF filtering
  app/services/proceeding_type_filter.rb
  spec/services/proceeding_type_filter_spec.rb
Labels: ready for review

#1516 Chore: Update Ruby and Alpine of base image
  .circleci/config.yml
  .ruby-version
  Dockerfile
  Gemfile.lock
Labels: ready for review

#1518 Fix: Update the PLF Specific Issue task name
  db/seed_data/proceeding_type_merits_task/public_law_family.yml
  spec/services/questions_service_spec.rb
Labels: ready for review

#1519 AP-5549: Split proceeding type merits tasks yaml files
  db/populators/proceeding_type_merits_task_populator.rb
  db/seed_data/proceeding_type_merits_task/domestic_abuse.yml
  db/seed_data/proceeding_type_merits_task/public_law_family.yml
  db/seed_data/proceeding_type_merits_task/section_8.yml
  db/seed_data/proceeding_type_merits_task/special_children_act.yml
Labels: ready for review
