Repository ministryofjustice/legal-framework-api, pull requests merged in 2025-01, with the labels that each got.

#1525 Chore: bump bundler 2.5.11 to 2.6.2
  Gemfile.lock
Labels: ready for review

#1522 AP-5659: bump ruby 3.3.6 to 3.4.1
  .circleci/config.yml
  .ruby-version
  Dockerfile
  Gemfile.lock
Labels: ready for review

#1527 Chore: Amend /status endpoint to use database_exists?
  app/controllers/status_controller.rb
  spec/requests/status_spec.rb
Labels: ready for review

#1524 AP-5666: Bump rails 7.2.2.1 to 8.0.1
  .github/dependabot.yml
  Gemfile
  Gemfile.lock
  bin/dev
  config/application.rb
  config/boot.rb
  config/environment.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/content_security_policy.rb
  config/initializers/cors.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/inflections.rb
  config/puma.rb
Labels: approved, UAT

#1531 Fix: Fix build step issue
  Dockerfile
Labels: ready for review

#1528 AP-5619: Add non means tested proceeding type filter
  app/models/proceeding_type.rb
  app/services/proceeding_type_filter.rb
  app/services/proceeding_type_full_text_search.rb
  config/initializers/inflections.rb
  db/migrate/20250109132817_add_non_means_tested_plf_to_proceeding_types.rb
  db/schema.rb
  db/seed_data/proceeding_types.yml
  spec/models/proceeding_type_spec.rb
  spec/requests/proceeding_types/searches_controller_swagger_spec.rb
  spec/services/proceeding_type_filter_spec.rb
  swagger/v1/swagger.yaml
Labels: approved, ready for review

#1534 AP-4305: Change PLF rules for Q6
  db/seed_data/proceeding_type_merits_task/public_law_family.yml
  spec/services/questions_service_spec.rb
Labels: ready for review

#1533 AP-5603: Remove unused proceeding SE099E
  app/models/proceeding_type.rb
  config/environments/test.rb
  lib/tasks/fixes/ap_5603.rake
  spec/lib/tasks/fixes_spec.rb
Labels: approved
